### ISSUE TITLE
Could we rename this repository to something else?

### ISSUE THREAD

**Issue by onbjerg** [aragon/apm-contracts#1]
This is really the package repository, not the package manager. The package manger is probably going to be something seperate(?) that does all of the publishing for the developer, sort of akin to npm.

In the light of that I think we should rename this repository. What are your thoughts?

**Comment by luisivan** [comment]
I'd say we rename it to _avp_, and then the CLI can be _apm_

**Comment by onbjerg** [comment]
Or apm-contracts, avp-contracts (just to clarify that it's contracts)

**Comment by luisivan** [comment]
Makes sense too

**Comment by izqui** [comment]
`apm-contracts` sounds fine

**Comment by onbjerg** [comment]
Closing since it was renamed 🎉
