### ISSUE TITLE
`Repo.getVersionsCount` returns incorrect length

### ISSUE THREAD

**Issue by onbjerg** [aragon/apm-contracts#6]
It should return `versions.length`, not `versions.length - 1`.

**Comment by izqui** [comment]
It returns the correct length. When the first version is created, an empty version is created at index 0 

https://github.com/aragon/apm-contracts/blob/0c92f1193104e712f934616a29586f7b2f421a0e/contracts/Repo.sol#L32

Therefore we need to subtract 1 from the length before returning if length is greater than 0.

https://github.com/aragon/apm-contracts/blob/ccea85e54ed54e6d33e3f96309b9e743efda96d7/contracts/Repo.sol#L62-L65

The reason this is done this way is, so these other two mappings that index depending on other factors indicate that a version doesn't exist if they return 0. 

https://github.com/aragon/apm-contracts/blob/ccea85e54ed54e6d33e3f96309b9e743efda96d7/contracts/Repo.sol#L13-L14

Adding a comment in the code clarifying this.

**Comment by onbjerg** [comment]
Makes sense, thanks
